// Leaf module: `schema.ts` reads it at load time. `defineProfile` enforces the requirements;
// this records them for display.

/** lexicon-exempt-file: authoring field-meta presence notes — not runtime user or model copy (P2) */

export interface ProfileFieldPresence {
  /** The profile must set the field: always (`true`), or only in the case named. */
  required?: true | string;
  /** What leaving the field out does, as a short phrase a blank control can show. */
  unset?: string;
}

/** Presence for profile paths, keyed like `PROFILE_FIELDS` (`models.*` matches every binding). */
export const PROFILE_FIELD_PRESENCE: Readonly<Record<string, ProfileFieldPresence>> = {
  id: { required: true },
  type: { required: true },
  identity: { required: true },
  'identity.handle': { required: true },
  'identity.system': { unset: 'No system instruction' },
  tools: { required: true },
  'tools.allow': { required: true },
  image: { required: true },
  speech: { required: true },
  live: { required: true },
  decision: { required: true },
  'decision.contract': { required: true },
  models: { required: true },
  defaultModel: { required: 'when more than one model is declared', unset: 'The only model' },
  allowModelSelect: { unset: 'Off' },
  maxSteps: { unset: 'Unbounded' },
  key: { required: 'when a Google model has no key of its own', unset: 'No key slot' },
  fallbackKey: { unset: 'No fallback' },
  'models.*.protocol': { required: true },
  'models.*.provider': { required: true },
  'models.*.apiId': { required: true },
  'models.*.builtInTools': { unset: 'None' },
  'models.*.maxOutputTokens': { unset: 'Provider default' },
  'models.*.temperature': { unset: 'Provider default' },
  'models.*.summaries': { unset: 'Provider default' },
  'models.*.efforts': { unset: 'Provider default' },
  'models.*.defaultEffort': {
    required: 'when more than one effort is declared',
    unset: 'The only effort',
  },
  'models.*.allowEffortSelect': { unset: 'Off' },
  'models.*.key': { unset: "The profile's key" },
  'models.*.fallbackKey': { unset: "The profile's fallback key" },
  'models.*.timeoutMs': { unset: 'No timeout' },
  'models.*.compaction': { unset: 'Off' },
  'models.*.compaction.maxTokens': { required: true },
  'models.*.compaction.compactAt': { required: true },
  'models.*.compaction.previousExchanges': { required: true },
  'models.*.compaction.profile': { required: true },
  'models.*.compaction.timing': { required: true },
  'models.*.compaction.meter': { unset: 'history' },
  'models.*.cache': { unset: 'Off' },
  'models.*.cache.mode': { required: true },
  'models.*.cache.ttl': { unset: 'Provider default' },
  'models.*.store': { unset: 'Provider default' },
  'models.*.persistViaInteractionId': { required: 'when the protocol is geminiInteractions' },
  inputs: { required: true },
  'inputs.text': { unset: 'Accepted' },
  'inputs.attachments.accept': { unset: 'No attachments' },
  'inputs.voice.accept': { unset: 'No voice' },
  'inputs.maxFiles': { required: 'when attachments or voice is set' },
  'inputs.maxBytes': { required: 'when attachments or voice is set' },
  'inputs.maxTurnBytes': { required: 'when attachments or voice is set' },
  'inputs.state': { required: true },
  'inputs.maxStateBytes': { unset: 'No cap' },
  'inputs.limitsByMime': { unset: 'maxBytes for every type' },
  'inputs.slots': { unset: 'No slots' },
  'outputs.structured': { unset: 'Free text' },
  'outputs.validation.maxRetries': { unset: '0' },
  'outputs.streaming.mode': { unset: 'sse' },
  'outputs.streaming.streamThoughts': { unset: 'On' },
  'turnBehaviour.resumption.allowContinue': { unset: 'All three' },
  'turnBehaviour.resumption.autoContinue': { unset: 'length and stream_incomplete' },
  'turnBehaviour.resumption.maxContinues': { unset: 'No cap' },
  'turnBehaviour.allowSteering': { unset: 'On' },
  'guardrails.quota': { unset: 'No limit' },
  'guardrails.canary': { unset: 'On' },
  'guardrails.sanitizeInput': { unset: 'On' },
  'guardrails.redactSensitive': { unset: 'On' },
  'guardrails.egress': { unset: 'No check' },
  'guardrails.egress.enforce': { required: 'when checks is not set' },
  'guardrails.egress.checks': { required: 'when enforce is not set' },
  'guardrails.egress.checks.sensitive': { unset: 'Every group but network' },
  'guardrails.egress.checks.sensitive.ids': { unset: 'On' },
  'guardrails.egress.checks.sensitive.financial': { unset: 'On' },
  'guardrails.egress.checks.sensitive.network': { unset: 'Off' },
  'guardrails.egress.checks.sensitive.credentials': { unset: 'On' },
  'guardrails.egress.checks.boundary': { unset: 'On' },
  'guardrails.egress.checks.injection': { unset: 'On' },
  'guardrails.egress.checks.images': { unset: 'On' },
  'guardrails.egress.checks.images.hosts': { unset: 'None' },
  'guardrails.egress.checks.images.fromTools': { unset: 'On' },
  'guardrails.egress.checks.links': { unset: 'Off' },
  'guardrails.egress.checks.links.hosts': { unset: 'The images hosts' },
  'guardrails.egress.checks.links.fromTools': { unset: 'On' },
  'guardrails.egress.onBlock': { unset: 'reject_to_agent' },
  'guardrails.egress.maxRetries': { unset: '0' },
  'guardrails.egress.holdback': { unset: '256' },
  'guardrails.network.allowPrivateNetworks': { unset: 'Off' },
  'guardrails.network.allowedHosts': { unset: 'None' },
  'guardrails.network.allowedSchemes': {
    unset: 'https, plus http when allowPrivateNetworks is on',
  },
  'guardrails.taint.afterRemoteRead': { unset: 'off' },
  'guardrails.disclosure': { unset: 'No check' },
  'observability.writeTo': { unset: 'No traces' },
  'observability.sampleRate': { unset: '1' },
  'observability.include.upstreamLog': { unset: 'On' },
  'observability.include.outboundWire': { unset: 'Off' },
  'observability.include.evidenceRaw': { unset: 'Off' },
  'observability.include.usage': { unset: 'On' },
  'observability.include.guardrailDecisions': { unset: 'On' },
  'observability.include.guardrailMatchPreview': { unset: 'Off' },
  'observability.resource': { unset: 'None' },
  'observability.scrub.sensitive': { unset: 'On' },
  'observability.scrub.injection': { unset: 'On' },
  'observability.scrub.canary': { unset: 'On' },
  'observability.retainForDays': { unset: '14' },
  'observability.rotateAfterMiB': { unset: '32' },
  'observability.onWriteError': { unset: 'Errors are dropped' },
  'image.aspectRatio': { unset: 'Provider default' },
  'image.resolution': { unset: 'Provider default' },
  'image.mimeType': { unset: 'Provider default' },
  'image.quality': { unset: 'Provider default' },
  'image.background': { unset: 'Provider default' },
  'image.n': { unset: 'Provider default' },
  'image.seed': { unset: 'Provider default' },
  'image.outputCompression': { unset: 'Provider default' },
  'image.references': { unset: 'None' },
  'image.includeText': { unset: 'Off' },
  'speech.voice': { unset: 'Provider default' },
  'speech.format': { unset: 'Provider default' },
  'live.ingress.audio': { unset: 'On' },
  'live.ingress.video': { unset: 'On' },
  'live.ingress.text': { unset: 'Off' },
  'live.voice': { unset: 'Provider default' },
  'live.vad.activityHandling': { unset: 'Provider default' },
  'live.vad.startSensitivity': { unset: 'Provider default' },
  'live.vad.endSensitivity': { unset: 'Provider default' },
  'live.vad.prefixPaddingMs': { unset: 'Provider default' },
  'live.vad.silenceDurationMs': { unset: 'Provider default' },
  'live.sessionResumption': { unset: 'Off' },
  'live.contextCompression': { unset: 'Off' },
  'live.contextCompression.triggerTokens': { unset: 'Provider default' },
  'live.contextCompression.slidingWindow': { required: true },
  'live.contextCompression.slidingWindow.targetTokens': { unset: 'Provider default' },
  'live.proactiveAudio': { unset: 'Off' },
  'live.transcription.input': { unset: 'Off' },
  'live.transcription.output': { unset: 'Off' },
};
