/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/ui/theorem-theme.ts
 * Command: astryx theme build src/ui/theorem-theme.ts --out src/ui/built/theme.css
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

import type { IconRegistry } from '@astryxdesign/core/Icon';
/// <reference path="./theorem.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const tablerIcons: IconRegistry;
export declare const theoremTheme: DefinedTheme;
