/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/ui/theorem-theme.ts
 * Command: astryx theme build src/ui/theorem-theme.ts --out src/ui/built/theme.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
