/**
 * Writes `src/guardrails/egress-automata.ts` from the bundled egress patterns
 * (`src/guardrails/egress-patterns.ts`):
 *
 * - `REVERSED_INJECTION_PATTERNS`: each injection pattern reversed, so text
 *   written backwards is matched as written.
 * - `FORWARD_AUTOMATON` / `REVERSED_AUTOMATON`: for each pattern, an automaton
 *   accepting every match of it and more, which the streaming hold runs to see
 *   where a match could still be under way (`egress-stream.ts`).
 *
 * The automata are built as `src/guardrails/egress-compiler.ts` describes.
 *
 *   deno run --allow-read --allow-write --allow-run scripts/gen-egress-automata.ts
 *
 * @module
 */

import { bundledEgressAutomata } from '../src/guardrails/egress-compiler.ts';
import type { EgressAutomatonData } from '../src/guardrails/egress-rules.ts';

const OUT = new URL('../src/guardrails/egress-automata.ts', import.meta.url);

function moduleText(): string {
  const data = bundledEgressAutomata();
  const table = (value: EgressAutomatonData): string =>
    `{\n  classStarts: ${JSON.stringify(value.classStarts)},\n  charsets: ${JSON.stringify(value.charsets)},\n  initials: ${JSON.stringify(value.initials)},\n  leads: ${JSON.stringify(value.leads)},\n  nodes: ${JSON.stringify(value.nodes)},\n}`;
  return `// deno-lint-ignore-file no-control-regex -- the reversed patterns spell out the classes they read, control characters included
// biome-ignore-all lint/suspicious/noControlCharactersInRegex: the reversed patterns spell out the classes they read, control characters included
// biome-ignore-all lint/correctness/noEmptyCharacterClassInRegex: \`[^]\` is any character, as the generator writes it
/**
 * Generated by \`scripts/gen-egress-automata.ts\` from \`egress-patterns.ts\`.
 * Do not edit: change the patterns and run the script.
 *
 * @module
 */

import type { EgressAutomatonData } from './egress-rules.ts';

/** Each injection pattern reversed: it matches where the pattern matches the text written backwards. */
const REVERSED_INJECTION_PATTERNS: RegExp[] = [
${data.reversedPatterns.map((re) => `  ${re.toString()},`).join('\n')}
];

/** Every egress pattern, loosened to a superset automaton, in \`EGRESS_PATTERNS\` order. */
const FORWARD_AUTOMATON: EgressAutomatonData = ${table(data.forward)};

/** Each reversed injection pattern, loosened the same way. */
const REVERSED_AUTOMATON: EgressAutomatonData = ${table(data.reversed)};

export { FORWARD_AUTOMATON, REVERSED_AUTOMATON, REVERSED_INJECTION_PATTERNS };
`;
}

if (import.meta.main) {
  await Deno.writeTextFile(OUT, moduleText());
  const fmt = new Deno.Command('npx', {
    args: ['biome', 'format', '--write', OUT.pathname],
    stdout: 'inherit',
    stderr: 'inherit',
  });
  if (!(await fmt.output()).success) Deno.exit(1);
}
