/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: ui/studio-theme.ts
 * Command: astryx theme build ui/studio-theme.ts --out ui/built/theme.css
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

/// <reference path="./theorem-studio.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const tablerIcons: IconRegistry;
export declare const theoremStudioTheme: DefinedTheme;
