/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: ui/studio-theme.ts
 * Command: astryx theme build ui/studio-theme.ts --out ui/built/theme.css
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Card' {
  interface CardVariantMap {
    'bubble': true;
  }
}

declare module '@astryxdesign/core/Section' {
  interface SectionVariantMap {
    'raised': true;
  }
}
