import type { IconName } from '@astryxdesign/core/Icon';
import {
	type Icon as TablerIcon,
	IconAlertTriangle,
	IconArrowDown,
	IconArrowsSort,
	IconArrowUp,
	IconCalendar,
	IconCheck,
	IconChecks,
	IconChevronDown,
	IconChevronLeft,
	IconChevronRight,
	IconChevronsLeft,
	IconChevronsRight,
	IconCircleCheck,
	IconCircleX,
	IconClock,
	IconColumns,
	IconCopy,
	IconDots,
	IconExternalLink,
	IconEyeOff,
	IconFilter,
	IconInfoCircle,
	IconMenu2,
	IconMicrophone,
	IconPlayerStopFilled,
	IconSearch,
	IconTool,
	IconX,
} from '@tabler/icons-react';
import { createElement, type ReactNode } from 'react';

const TABLER_BY_NAME: Record<IconName, TablerIcon> = {
	close: IconX,
	chevronDown: IconChevronDown,
	chevronLeft: IconChevronLeft,
	chevronRight: IconChevronRight,
	chevronsLeft: IconChevronsLeft,
	chevronsRight: IconChevronsRight,
	check: IconCheck,
	success: IconCircleCheck,
	error: IconCircleX,
	warning: IconAlertTriangle,
	info: IconInfoCircle,
	calendar: IconCalendar,
	clock: IconClock,
	externalLink: IconExternalLink,
	menu: IconMenu2,
	moreHorizontal: IconDots,
	search: IconSearch,
	arrowUp: IconArrowUp,
	arrowDown: IconArrowDown,
	arrowsUpDown: IconArrowsSort,
	funnel: IconFilter,
	eyeSlash: IconEyeOff,
	viewColumns: IconColumns,
	copy: IconCopy,
	checkDouble: IconChecks,
	wrench: IconTool,
	stop: IconPlayerStopFilled,
	microphone: IconMicrophone,
};

/** Astryx semantic icon registry drawn from Tabler (replaces neutral's lucide set). */
export const tablerIcons = Object.fromEntries(
	Object.entries(TABLER_BY_NAME).map(([name, Glyph]) => [
		name,
		createElement(Glyph, { size: '1em', stroke: 1.75, 'aria-hidden': true }),
	]),
) as Record<IconName, ReactNode>;
